# Generated by Django 3.1.6 on 2021-02-17 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=254)),
                ('cityNameEn', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(max_length=254)),
                ('ca', models.IntegerField()),
                ('effectif', models.IntegerField()),
                ('organizationPresentation', models.CharField(max_length=254)),
                ('organizationCountryCounter', models.IntegerField()),
                ('organizationExpertise', models.CharField(max_length=254)),
                ('organizationCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=254)),
                ('contactEmail', models.CharField(max_length=508)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='civiweb.company')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=254)),
                ('countryNameEn', models.CharField(max_length=254)),
                ('countryCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeographicZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geographicZoneLabel', models.CharField(max_length=254)),
                ('geographicZoneLabelEn', models.CharField(max_length=254)),
                ('geographicCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerCode', models.CharField(max_length=254)),
                ('active', models.BooleanField()),
                ('missionTitle', models.CharField(max_length=508)),
                ('missionDuration', models.IntegerField()),
                ('viewCounter', models.IntegerField()),
                ('candidateCounter', models.IntegerField()),
                ('missionType', models.CharField(max_length=254)),
                ('missionTypeEn', models.CharField(max_length=254)),
                ('missionDescription', models.CharField(max_length=10000)),
                ('creationDate', models.DateField(null=True)),
                ('missionStartDate', models.DateField(null=True)),
                ('missionEndDate', models.DateField(null=True)),
                ('startBroadcastDate', models.DateField(null=True)),
                ('durationBroadcast', models.IntegerField()),
                ('missionProfile', models.CharField(max_length=10000)),
                ('reference', models.CharField(max_length=254)),
                ('indemnite', models.IntegerField()),
                ('idMotifDesactivationOffre', models.IntegerField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='civiweb.city')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='civiweb.contact')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='civiweb.country')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='civiweb.company')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='geographicZone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='civiweb.geographiczone'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='civiweb.country'),
        ),
    ]
