# Generated by Django 3.1.6 on 2021-02-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civiweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='organizationExpertise',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='organizationPresentation',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactEmail',
            field=models.CharField(max_length=508, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='missionDescription',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='missionProfile',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='missionType',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='missionTypeEn',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='reference',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
