# Generated by Django 3.1.6 on 2021-02-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civiweb', '0002_auto_20210219_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ca',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='effectif',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='organizationCountryCounter',
            field=models.IntegerField(null=True),
        ),
    ]
