# Generated by Django 3.1.6 on 2021-02-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civiweb', '0003_auto_20210219_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='creationDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='missionEndDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='missionStartDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='startBroadcastDate',
            field=models.DateTimeField(null=True),
        ),
    ]
