# Generated by Django 3.1.6 on 2021-02-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civiweb', '0004_auto_20210219_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityNameEn',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='countryNameEn',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
