# Generated by Django 3.1.6 on 2021-03-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civiweb', '0006_auto_20210219_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='candidateCounter',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='durationBroadcast',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='missionDescription',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='missionEndDate',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='missionStartDate',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='missionType',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='missionTypeEn',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='startBroadcastDate',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='viewCounter',
        ),
    ]
