# Generated by Django 3.1.6 on 2021-03-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civiweb', '0008_auto_20210301_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
